### ISSUE TITLE
用tensorrt导出模型后，推理精度有所降低，会出现误判的情况，请问up有遇到过类似的情况吗？

### ISSUE THREAD

**Issue by wsy-yjys** [LSH9832/yolov8_trt#2]

**Comment by wsy-yjys** [comment]
--fp16，int8,  best 这三个参数应该怎么选呀？如何在不牺牲精度的情况下提升速度？

**Comment by LSH9832** [comment]
三个都不填是精度最高的，模型转化时将不会降低浮点数的精度，但是基本没有速度提升，--fp16牺牲少量精度能够大量提升速度，--int8和--best能够提升速度更多，但是精度降低会比较明显，需要进行校准训练。
